### ISSUE TITLE
Improve the aesthetics/look of the website

### ISSUE THREAD

**Issue by rozsasarpi** [martinig94/reliability_workshop_2020#1]
- [x] harmonize fonts 
- [x] update the parallax overlay images
- [x] decrease the top navbar padding around the icon
- [x] SVG icon/logo
- [x] shorter footer
- [x] dotted background

**Comment by martinig94** [comment]
- [ ] CNAME already taken

**Comment by martinig94** [comment]
Check the new font. it `s the same as the main title. I do not really like, so let me know what you would like to have @rozsasarpi
